Base:
    depth_path: /home/pcl/mesh/LivoMesh/data/FAST_LIVO2/test/fast_livo_xiaojuchang.pcd
    save_pcd_en: true
    output_pcd_path: /home/pcl/mesh/LivoMesh/output/test_binary_output.pcd

Filter:
    enable: true
    Radius: 0.13
    Max error: 1.0
    remove_isolated: true
